## ECG analysis steps

The goal of this project is to load, check and visualize ECG data.

The main steps are:
1. Load the raw ECG data.
2. Check that the data were loaded correctly.
3. Plot the raw ECG signal.
4. Rescale the ECG data to standard units.
5. Plot the rescaled ECG signal.
6. Improve the code to make it clearer and easier to reuse.

In [3]:
import numpy as np 
import matplotlib.pyplot as plt


In [4]:
raw_ecg = np.loadtxt("data/ECGu.txt")

In [5]:
print(raw_ecg)
print(raw_ecg.shape)

[[-275. -119. -119.]
 [-275. -119. -119.]
 [-275. -118. -121.]
 ...
 [  -4.  -83.   21.]
 [  -9.  -88.   31.]
 [ -16.  -96.   33.]]
(6500, 3)
